'''def suma(n1,n2):
	FUNCION CON PARÁMETROS DE TIPO NUMÉRICO
	print(n1+n2)

suma(3,7)

suma(3,0)

suma(2,33)'''

def suma(n1,n2):
	resultado=n1+n2
	return resultado

'''print(suma(3,5))''' # AL MARCARLE UN RETURN DEBEMOS AÑADIR PRINT A LOS PARÁMETROS

almacena_resultado=suma(4,7)

print(almacena_resultado) 
'''CREAMOS UNA VARIABLE QUE NOS ALMACENE RESULTADO, 
LE DECIMOS QUE ES IGUAL A LA FUNCION SUMA Y LE AÑADIMOS LOS 2 ARGUMENTOS,
DESPUÉS LE DECIMOS QUE NOS IMPRIMA LA VARIABLE DONDE SE ALMACENA EL RESULTADO
Y NOS DARÁ LA SUMA ALMACENADA. ES MUY ÚTIL PARA ALMACENAR RESULTADOS EN VARIABLES'''

